apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: microservices
build:
  local:
    push: false
  artifacts:
    - image: z1maka/auth_service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: z1maka/ticket_service
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: z1maka/client_service
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*js"
            dest: .
    - image: z1maka/order_service
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
