apiVersion: v1
kind: Service
metadata:
  name: order-srv
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - port: 3000
      name: order
      targetPort: 3000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: z1maka/order_service
          env:
            - name: NATS_URI
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "z1maka"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://order-mongo-srv:27017/order"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret
